package com.spt.bas.client.constant;

/**
 * 角色权限枚举类
 *
 * @Author MoonLight
 * @Date 2023/6/12 9:22
 * @Version 1.0
 */
public enum PermissionEnum {
    ZGBAS_VIRE_ALL_COMPLAINTS("zgbas:view:all:complaints", "查询所有投诉信息"),
    ZGBAS_VIEW_CENTER_COMPLAINTS("zgbas:center:principal", "中心负责人"),
    APPROVE_START("bas:approve:start", "审批开始权限"),
    APPROVE_VIEW_ALL("bas:approve:viewall", "查看所有审批单权限"),
    APPROVE_BUSINESS_VIEW_ALL("bas:approve:business:viewAll", "查看所有业务审批单权限"),
    PERM_COMPANY_DEPT_LEADER("bas:company:dept:leader", "区域总企业操作权限"),
    PERM_CUST_VIEWALL("bas:company:viewall", "查看所有企业权限"),
    PERM_BUSINESS_HHR("bas:business:hhr", "业务合伙人权限"),
    PERM_COMPANY_VIEWDEPT("bas:company:viewDept", "查看本部门客户"),
    PERM_CUST_VIEWBL("bas:company:viewfactor", "查看所有的保理合同"),
    PERM_CUST_DELETE("bas:company:delete", "删除企业权限"),
    PERM_CUST_OPERATION("bas:company:operation", "只可查看不可操作企业信息"),
    PERM_COMPANY_EDIT("bas:company:edit", "客户编辑权限"),
    APPROVE_WITHDRAW("bas:approve:withdraw", "审批撤回"),
    APPROVE_IN_INVALID("bas:deliveryin:invalid", "入库单作废"),
    APPROVE_OUT_INVALID("bas:deliveryout:invalid", "出库单作废"),
    APPROVE_PAY_INVALID("bas:pay:invalid", "付款单作废"),
    APPROVE_FUND_RECHARGE_INVALID("bas:fundRecharge:invalid", "资金方充值单作废"),
    APPROVE_DCSX_PAY_INVALID("bas:dcsxPay:invalid", "代采赊销付款作废"),
    APPROVE_FUND_RECHARGE("bas:fundRecharge:apply", "资金方充值权限"),
    APPROVE_RECEIVE_INVALID("bas:receive:invalid", "收款单作废"),
    APPROVE_INVOICE_INVALID("bas:invoice:invalid", "开票单作废"),
    APPROVE_INVOICERECEIVE_INVALID("bas:invoicereceive:invalid", "收票单作废"),
    APPROVE_CONFIRMRECEIPT_INVALID("bas:confirmReceipt:invalid", "确认收货单作废"),
    APPROVE_CONFIRMRECEIPTDCSX_INVALID("bas:confirmReceiptDcsx:invalid", "中游确认收货单作废"),
    APPROVE_CTR_CANCEL("bas:ctr:cancel", "合同作废权限"),
    PERM_CTR_VIEWALL("bas:ctr:viewall", "新:审批-查看所有合同"),
    PERM_ADMIN_NEW("bas:admin:new", "审批管理员"),
    PERM_NOTICE_ADDANDEDIT("bas:notice:addAndedit", "公告管理新增编辑权限"),
    PERM_CTR_ADJUST("bas:ctr:adjust", "合同调整权限"),
    PERM_CTR_CAN_NOTIFY("bas:ctr:cannotify", "逾期通知权限"),
    APPROVE_CTR_UPDATE_STOCKTYPE("bas:stockdetail:update", "更改库存类型权限"),
    PERM_CTR_VIEWPRESELL("bas:ctr:viewpresell", "查看本中心所有预售合同权限"),
    PERM_CTR_CONFIRM("bas:ctr:confirm", "确认收货权限"),
    PERM_CTR_CLEAR_PENALTY("bas:ctr:clearPenalty", "清除罚金权限"),
    PERM_CTR_EXPORT("bas:ctr:export", "导出合同Excel权限"),
    PERM_CTR_EXPORT_SIGN("bas:ctr:export:sign", "导出合同双签权限"),
    PERM_CTR_EXPORT_BUYANDSELL("bas:ctr:export:buyAndSell", "导出合同上下游权限"),
    PERM_CTR_EXPORT_BUSINESS("bas:ctr:export:business", "导出业务表权限"),
    PERM_CTR_PREVIEW("bas:ctr:preview", "合同预览权限"),
    PERM_COMPANY_EXPORT("bas:company:export", "企业导出Excel权限"),
    PERM_COMPANY_EXPORT_ACCESS_REPORT("bas:company:export:access:report", "企业导出访厂报告权限"),
    PERM_COMPANY_EXPORT_CREDIT_INF0_0("bas:company:export:credit:info:0", "导出人保授信客户"),
    PERM_CTR_SIGNING("bas:ctr:signing", "合同签约权限"),
    PERM_CTR_REFRESH_CONTRACT("bas:ctr:refreshContract", "刷新电子合同"),
    PERM_CTR_INTEREST("bas:ctr:interest", "罚息输入权限"),
    PERM_CTR_DELETE_FILEID("bas:ctr:deleteFileId", "删除合同附件权限"),
    PERM_STOCK_MOVESTOCK("bas:stock:movestock", "移库权限"),
    PERM_ORVERDUR_NOTICE("bas:orverdur:receiveNotice", "收款逾期通知权限"),
    PERM_SEAL_BORROW("bas:seal:borrow", "印章外借归还权限"),
    PERM_COMPANY_EPX("bas:company:epx", "客户数据导出"),
    PERM_CONFIG_VIEW("bas:config:view", "业务配置项查询权限"),
    PERM_COMPANY_WFQAUTH("bas:company:wfqAuth", "微风企授权"),
    PERM_COMPANY_WFQ_VIEWDATA("bas:company:wfq:viewdata", "微风企数据查看"),
    PERM_COMPANY_IMPORT_PICCDATA("bas:company:import:piccdata", "导入人保授信数据权限"),
    PERM_COMPANY_IMPORT_DADI_AMOUNT("bas:company:import:dadi:amount", "导入大地额度数据权限"),
    PERM_COMPANY_IMPORT_ZHONGYIN_AMOUNT("bas:company:import:zhongyin:amount", "导入中银额度数据权限"),
    PERM_COMPANY_IMPORT_CREDIT_REPORT("bas:company:import:credit:report", "征信报告导入权限"),
    PERM_BS_COMPANYDCSX_IMPORT_INSURANCE("bs:companyDcsx:import:insurance", "人保保费流水导入权限"),
    PERM_COMPANY_VIEWDETAIL("bas:company:viewdetail", "查看客户详情"),
    BAS_ADDITIONAL_MANAGER("bas:additional:manager", "追加经办人"),
    PERM_EVALUATE_VIEWDETAIL("bas:evaluate:viewall", "查看所有考核明细"),
    PERM_EVALUATE_SH("bas:evaluate:sh", "查看上海考核明细"),
    PERM_EVALUATE_QD("bas:evaluate:qd", "查看青岛考核明细"),
    PERM_EVALUATE_GZ("bas:evaluate:gz", "查看广州考核明细"),
    PERM_EVALUATE_YY("bas:evaluate:yy", "查看余姚考核明细"),
    PERAM_BATCH_APPROVE("bas:batch:approve", "批量审批一键同意权限"),
    PERAM_EXPORT_APPROVE("bas:export:approve", "审批列表导出"),
    PERAM_BATCH_SELECT_DEL("bas:batch:selectDel", "查询删除审批单"),
    VIOLATETREATYFLG_UPDATE("bas:violateTreatyFlg:update", "业务配置项查询权限"),
    CTR_DCSXUPDATEFILEID_FLG("bas:ctr:dcsxupdatafileid", "代采赊销更新合同附件权限"),
    CONTRACT_UPDATECOSTFLG("bas:contract:updateCostFlgd", "费用调整权限"),
    PERM_VIEW_ALL_SIGN_FILE("bas:viewAllSignFile", "查询所有文件签署"),
    BAS_PERFORMANCE_ALL("bas:performance:all", "首页-查看全体业绩排行权限"),
    BAS_INDEX_RISKSTATISTICS("bas:index:riskStatistics", "首页-查看风控统计权限"),
    BAS_INDEX_FINANCESTATISTICS("bas:index:financeStatistics", "首页-查看财务统计权限"),
    BAS_INDEX_UNPAYSTATISTICS("bas:index:unPayStatistics", "首页-查看未收款统计权限"),
    BAS_PERFORMANCECOMMISSION_ALL("bas:performanceCommission:all", "首页-查看所有业绩提成"),
    BAS_INDEX_GROSSPROFITMARGIN("bas:index:grossProfitMargin", "首页-毛利率查看权限"),
    PERM_WORK_BENCH_VIEW("zgbas:work:bench:view", "查看我的工作台权限"),
    PERM_BUSINESS_OVERVIEW_VIEW("zgbas:business:overview:view", "查看业务总览权限"),
    BAS_PERFORMANCE_SETTLEMENT("bas:performance:settlement", "提成明细表结算权限"),
    BAS_PERFORMANCE_FINALACCOUNT("bas:finaAccount:settlement", "提成明细表决算权限"),
    BAS_PERFORMANCE_VIEWALLSETTLEMENT("bas:viewAll:settlement", "查看所有提成明细数据权限"),
    BAS_EVALUATE_AUDIT("bas:evaluate:audit", "考核审核权限"),
    //    ---------------------------------------------------------------------------------
    ZGBAS_BUSINESSLEDGER_FUNDER("zgbas:businessLedger:funder", "资金方业务台账查看权限"),
    ZGBAS_BASECOST_HD("zgbas:baseCost:HD", "业务成本统计华东数据查看"),
    ZGBAS_BASECOST_HB("zgbas:baseCost:HB", "业务成本统计华北数据查看"),
    ZGBAS_BASECOST_HN("zgbas:baseCost:HN", "业务成本统计华南数据查看"),
    ZGBAS_BASECOST_HDO("zgbas:baseCost:HDO", "业务成本统计华东其他数据查看"),
    ZGBAS_BASECOST_HZ("zgbas:baseCost:HZ", "业务成本统计华中数据查看"),
    ZGBAS_BASECOST_OT("zgbas:baseCost:OT", "业务成本统计其它区域数据查看"),
    ZGBAS_BASECOST_NB("zgbas:baseCost:NB", "业务成本统计宁波事业部数据查看"),
    ZGBAS_BASECOST_JX("zgbas:baseCost:JX", "业务成本统计莒县事业部数据查看"),
    ZGBAS_PAY_BATCH_APPLY("zgbas:pay:batch:apply", "付款审批批量申请"),
    USER_ZL("zgbas:new:user:zl", "业务助理"),
    ZGBAS_BIZ_OPE("zgbas:biz:ope", "业务操作权限"),
    BAS_APPROVE_NOALLTYPE("bas:approve:noAllType", "无全部选项用户"),
    ZGBAS_NEW_USER_FUNDER("zgbas:new:user:funder", "资金方权限"),
    ZGBAS_PERSONNER_ADMIN("zgbas:personnel:admin", "人事管理员"),
    ZGBAS_EXECUTIVES_USER("zgbas:new:executives:user", "各部门负责人(高管)"),
    ZGBAS_NEW_GCY("zgbas:new:gcy", "观察员"),
    ZGBAS_NEW_RISK("zgbas:new:risk", "风控业务员"),
    ADMIN("admin", "超级管理员"),
    WS_CS_ROLE("ws:cs:role", "浙塑财务查看权限"),
    RISK_FN_ROLE("risk:fn:role", "风控系统财务菜单"),
    ZGBASADMIN("zgbasAdmin", "中光审批管理员"),
    ZGBAS_NEW_SALESMAN("zgbas:new:salesman", "业务员"),
    ZGBAS_NEW_MANAGER("zgbas:new:manager", "业务员"),
    ZGBAS_STATENENT("zgbas:statenent", "业务报表数据查看权限"),
    ZGBAS_STATENENT_DEPT("zgbas:statenent:dept", "业务报表数据查看本部门权限"),
    PERM_STOCK_INQUIRY("bas:index:stockInquiry", "首页库存查询权限"),
    ZGBAS_VIEWALL_VIRTUAL_BOOK("zgbas:viewAll:virtualBook", "查看所有库存台账权限"),
    ZGBAS_VIEWALL_VIRTUAL("zgbas:viewAll:virtual", "查看所有采购申请权限"),
    ZGBAS_VIEWALL_FUND_RECE_STATISTICS("zgbas:viewAll:fundReceivableStatistics", "查看所有资金方应收统计"),
    ZGBAS_VIEWALL_INVOICE_BILL_STATISTICS("zgbas:viewAll:invoiceBillStatistics", "查看所有资金方开票统计"),
    PERM_REPORT_SERVICE_DATA_SUM_EXPORT("bas:report:serviceDataSum:export", "业务数据汇总导出"),
    PERM_REPORT_MATCH_USER_STATISTICS_EXPORT("bas:report:matchUserStatistics:export", "业务员统计导出"),
    PERM_REPORT_MATCH_USER_COST_STATISTICS_EXPORT("bas:report:matchUserCostStatistics:export", "业务员成本统计导出"),
    PERM_REPORT_USER_ROI_EXPORT("bas:report:userRoi:export", "人员ROI报表导出"),
    PERM_REPORT_USER_ROI_SUM_EXPORT("bas:report:userRoiSum:export", "ROI汇总表导出"),
    PERM_REPORT_COMPANY_ANALYSE_EXPORT("bas:report:companyAnalyse:export", "客户数据分析导出"),
    PERM_REPORT_SUPPLIIER_ANALYSE_EXPORT("bas:report:supplierAnalyse:export", "供应商分析表导出"),
    PERM_REPORT_CREDIT_MONITOR_EXPORT("bas:report:creditMonitor:export", "授信额度监控导出"),
    PERM_REPORT_FUND_RECEIVABLE_STATISTICS_EXPORT("bas:report:fundReceivableStatistics:export", "资金方应收统计导出"),
    PERM_BUSINESS_MANAGER_WORK_BENCH_VIEW("zgbas:business:manager:work:bench:view", "业务经理工作台"),
    PERM_BUSINESS_MANAGER_WORKBENCH_SHOW_ALL("zgbas:business:manager:workbench:show:all", "业务经理工作台查看全部权限"),
    PERM_BAS_COMPANY_ASSIGNED("bas:company:assigned", "企业指派权限"),
    PERM_BAS_COMPANY_SHARE("bas:company:share", "企业分享权限"),
    PERM_BAS_COMPANY_RELEASE("bas:company:release", "企业释放权限"),
    PERM_BAS_COMPANY_ASSIGN("bas:company:assign", "企业分配权限"),
    PERM_BAS_COMPANY_LEADER_EXPORT("bas:company:leader:export", "区域总导出企业权限（开户人是本区域公海）"),
    PERM_ZGBAS_CUSTOMER_DEPT_VIEW("zgbas:customerDept:view", "改性塑料事业部数据查询权限"),
    ;
    private final String permissionCode;
    private final String permissionName;

    public String getPermissionCode() {
        return permissionCode;
    }

    public String getPermissionName() {
        return permissionName;
    }

    PermissionEnum(String permissionCode, String permissionName) {
        this.permissionCode = permissionCode;
        this.permissionName = permissionName;
    }
}
