package com.spt.bas.report.client.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RptCtrContractRelaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public RptCtrContractRelaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdIsNull() {
            addCriterion("buy_contract_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdIsNotNull() {
            addCriterion("buy_contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdEqualTo(Long value) {
            addCriterion("buy_contract_id =", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdNotEqualTo(Long value) {
            addCriterion("buy_contract_id <>", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdGreaterThan(Long value) {
            addCriterion("buy_contract_id >", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_contract_id >=", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdLessThan(Long value) {
            addCriterion("buy_contract_id <", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdLessThanOrEqualTo(Long value) {
            addCriterion("buy_contract_id <=", value, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdIn(List<Long> values) {
            addCriterion("buy_contract_id in", values, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdNotIn(List<Long> values) {
            addCriterion("buy_contract_id not in", values, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdBetween(Long value1, Long value2) {
            addCriterion("buy_contract_id between", value1, value2, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyContractIdNotBetween(Long value1, Long value2) {
            addCriterion("buy_contract_id not between", value1, value2, "buyContractId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdIsNull() {
            addCriterion("buy_product_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdIsNotNull() {
            addCriterion("buy_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdEqualTo(Long value) {
            addCriterion("buy_product_id =", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdNotEqualTo(Long value) {
            addCriterion("buy_product_id <>", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdGreaterThan(Long value) {
            addCriterion("buy_product_id >", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_product_id >=", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdLessThan(Long value) {
            addCriterion("buy_product_id <", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdLessThanOrEqualTo(Long value) {
            addCriterion("buy_product_id <=", value, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdIn(List<Long> values) {
            addCriterion("buy_product_id in", values, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdNotIn(List<Long> values) {
            addCriterion("buy_product_id not in", values, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdBetween(Long value1, Long value2) {
            addCriterion("buy_product_id between", value1, value2, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyProductIdNotBetween(Long value1, Long value2) {
            addCriterion("buy_product_id not between", value1, value2, "buyProductId");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNull() {
            addCriterion("buy_price is null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNotNull() {
            addCriterion("buy_price is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceEqualTo(BigDecimal value) {
            addCriterion("buy_price =", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotEqualTo(BigDecimal value) {
            addCriterion("buy_price <>", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThan(BigDecimal value) {
            addCriterion("buy_price >", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buy_price >=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThan(BigDecimal value) {
            addCriterion("buy_price <", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buy_price <=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIn(List<BigDecimal> values) {
            addCriterion("buy_price in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotIn(List<BigDecimal> values) {
            addCriterion("buy_price not in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buy_price between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buy_price not between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIsNull() {
            addCriterion("buy_user_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIsNotNull() {
            addCriterion("buy_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdEqualTo(Long value) {
            addCriterion("buy_user_id =", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotEqualTo(Long value) {
            addCriterion("buy_user_id <>", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdGreaterThan(Long value) {
            addCriterion("buy_user_id >", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_user_id >=", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdLessThan(Long value) {
            addCriterion("buy_user_id <", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdLessThanOrEqualTo(Long value) {
            addCriterion("buy_user_id <=", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIn(List<Long> values) {
            addCriterion("buy_user_id in", values, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotIn(List<Long> values) {
            addCriterion("buy_user_id not in", values, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdBetween(Long value1, Long value2) {
            addCriterion("buy_user_id between", value1, value2, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotBetween(Long value1, Long value2) {
            addCriterion("buy_user_id not between", value1, value2, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIsNull() {
            addCriterion("buy_user_name is null");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIsNotNull() {
            addCriterion("buy_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameEqualTo(String value) {
            addCriterion("buy_user_name =", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotEqualTo(String value) {
            addCriterion("buy_user_name <>", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameGreaterThan(String value) {
            addCriterion("buy_user_name >", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("buy_user_name >=", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLessThan(String value) {
            addCriterion("buy_user_name <", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLessThanOrEqualTo(String value) {
            addCriterion("buy_user_name <=", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLike(String value) {
            addCriterion("buy_user_name like", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotLike(String value) {
            addCriterion("buy_user_name not like", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIn(List<String> values) {
            addCriterion("buy_user_name in", values, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotIn(List<String> values) {
            addCriterion("buy_user_name not in", values, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameBetween(String value1, String value2) {
            addCriterion("buy_user_name between", value1, value2, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotBetween(String value1, String value2) {
            addCriterion("buy_user_name not between", value1, value2, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyDateIsNull() {
            addCriterion("buy_date is null");
            return (Criteria) this;
        }

        public Criteria andBuyDateIsNotNull() {
            addCriterion("buy_date is not null");
            return (Criteria) this;
        }

        public Criteria andBuyDateEqualTo(Date value) {
            addCriterion("buy_date =", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateNotEqualTo(Date value) {
            addCriterion("buy_date <>", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateGreaterThan(Date value) {
            addCriterion("buy_date >", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("buy_date >=", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateLessThan(Date value) {
            addCriterion("buy_date <", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateLessThanOrEqualTo(Date value) {
            addCriterion("buy_date <=", value, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateIn(List<Date> values) {
            addCriterion("buy_date in", values, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateNotIn(List<Date> values) {
            addCriterion("buy_date not in", values, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateBetween(Date value1, Date value2) {
            addCriterion("buy_date between", value1, value2, "buyDate");
            return (Criteria) this;
        }

        public Criteria andBuyDateNotBetween(Date value1, Date value2) {
            addCriterion("buy_date not between", value1, value2, "buyDate");
            return (Criteria) this;
        }

        public Criteria andSellContractIdIsNull() {
            addCriterion("sell_contract_id is null");
            return (Criteria) this;
        }

        public Criteria andSellContractIdIsNotNull() {
            addCriterion("sell_contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellContractIdEqualTo(Long value) {
            addCriterion("sell_contract_id =", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotEqualTo(Long value) {
            addCriterion("sell_contract_id <>", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdGreaterThan(Long value) {
            addCriterion("sell_contract_id >", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_contract_id >=", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdLessThan(Long value) {
            addCriterion("sell_contract_id <", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdLessThanOrEqualTo(Long value) {
            addCriterion("sell_contract_id <=", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdIn(List<Long> values) {
            addCriterion("sell_contract_id in", values, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotIn(List<Long> values) {
            addCriterion("sell_contract_id not in", values, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdBetween(Long value1, Long value2) {
            addCriterion("sell_contract_id between", value1, value2, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotBetween(Long value1, Long value2) {
            addCriterion("sell_contract_id not between", value1, value2, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdIsNull() {
            addCriterion("sell_product_id is null");
            return (Criteria) this;
        }

        public Criteria andSellProductIdIsNotNull() {
            addCriterion("sell_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellProductIdEqualTo(Long value) {
            addCriterion("sell_product_id =", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdNotEqualTo(Long value) {
            addCriterion("sell_product_id <>", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdGreaterThan(Long value) {
            addCriterion("sell_product_id >", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_product_id >=", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdLessThan(Long value) {
            addCriterion("sell_product_id <", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdLessThanOrEqualTo(Long value) {
            addCriterion("sell_product_id <=", value, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdIn(List<Long> values) {
            addCriterion("sell_product_id in", values, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdNotIn(List<Long> values) {
            addCriterion("sell_product_id not in", values, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdBetween(Long value1, Long value2) {
            addCriterion("sell_product_id between", value1, value2, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellProductIdNotBetween(Long value1, Long value2) {
            addCriterion("sell_product_id not between", value1, value2, "sellProductId");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNull() {
            addCriterion("sell_price is null");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNotNull() {
            addCriterion("sell_price is not null");
            return (Criteria) this;
        }

        public Criteria andSellPriceEqualTo(BigDecimal value) {
            addCriterion("sell_price =", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotEqualTo(BigDecimal value) {
            addCriterion("sell_price <>", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThan(BigDecimal value) {
            addCriterion("sell_price >", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sell_price >=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThan(BigDecimal value) {
            addCriterion("sell_price <", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sell_price <=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceIn(List<BigDecimal> values) {
            addCriterion("sell_price in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotIn(List<BigDecimal> values) {
            addCriterion("sell_price not in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sell_price between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sell_price not between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellUserIdIsNull() {
            addCriterion("sell_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSellUserIdIsNotNull() {
            addCriterion("sell_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellUserIdEqualTo(Long value) {
            addCriterion("sell_user_id =", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdNotEqualTo(Long value) {
            addCriterion("sell_user_id <>", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdGreaterThan(Long value) {
            addCriterion("sell_user_id >", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_user_id >=", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdLessThan(Long value) {
            addCriterion("sell_user_id <", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdLessThanOrEqualTo(Long value) {
            addCriterion("sell_user_id <=", value, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdIn(List<Long> values) {
            addCriterion("sell_user_id in", values, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdNotIn(List<Long> values) {
            addCriterion("sell_user_id not in", values, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdBetween(Long value1, Long value2) {
            addCriterion("sell_user_id between", value1, value2, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserIdNotBetween(Long value1, Long value2) {
            addCriterion("sell_user_id not between", value1, value2, "sellUserId");
            return (Criteria) this;
        }

        public Criteria andSellUserNameIsNull() {
            addCriterion("sell_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSellUserNameIsNotNull() {
            addCriterion("sell_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSellUserNameEqualTo(String value) {
            addCriterion("sell_user_name =", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameNotEqualTo(String value) {
            addCriterion("sell_user_name <>", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameGreaterThan(String value) {
            addCriterion("sell_user_name >", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("sell_user_name >=", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameLessThan(String value) {
            addCriterion("sell_user_name <", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameLessThanOrEqualTo(String value) {
            addCriterion("sell_user_name <=", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameLike(String value) {
            addCriterion("sell_user_name like", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameNotLike(String value) {
            addCriterion("sell_user_name not like", value, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameIn(List<String> values) {
            addCriterion("sell_user_name in", values, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameNotIn(List<String> values) {
            addCriterion("sell_user_name not in", values, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameBetween(String value1, String value2) {
            addCriterion("sell_user_name between", value1, value2, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellUserNameNotBetween(String value1, String value2) {
            addCriterion("sell_user_name not between", value1, value2, "sellUserName");
            return (Criteria) this;
        }

        public Criteria andSellDateIsNull() {
            addCriterion("sell_date is null");
            return (Criteria) this;
        }

        public Criteria andSellDateIsNotNull() {
            addCriterion("sell_date is not null");
            return (Criteria) this;
        }

        public Criteria andSellDateEqualTo(Date value) {
            addCriterion("sell_date =", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateNotEqualTo(Date value) {
            addCriterion("sell_date <>", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateGreaterThan(Date value) {
            addCriterion("sell_date >", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateGreaterThanOrEqualTo(Date value) {
            addCriterion("sell_date >=", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateLessThan(Date value) {
            addCriterion("sell_date <", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateLessThanOrEqualTo(Date value) {
            addCriterion("sell_date <=", value, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateIn(List<Date> values) {
            addCriterion("sell_date in", values, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateNotIn(List<Date> values) {
            addCriterion("sell_date not in", values, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateBetween(Date value1, Date value2) {
            addCriterion("sell_date between", value1, value2, "sellDate");
            return (Criteria) this;
        }

        public Criteria andSellDateNotBetween(Date value1, Date value2) {
            addCriterion("sell_date not between", value1, value2, "sellDate");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdIsNull() {
            addCriterion("stock_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdIsNotNull() {
            addCriterion("stock_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdEqualTo(Long value) {
            addCriterion("stock_detail_id =", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdNotEqualTo(Long value) {
            addCriterion("stock_detail_id <>", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdGreaterThan(Long value) {
            addCriterion("stock_detail_id >", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stock_detail_id >=", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdLessThan(Long value) {
            addCriterion("stock_detail_id <", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdLessThanOrEqualTo(Long value) {
            addCriterion("stock_detail_id <=", value, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdIn(List<Long> values) {
            addCriterion("stock_detail_id in", values, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdNotIn(List<Long> values) {
            addCriterion("stock_detail_id not in", values, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdBetween(Long value1, Long value2) {
            addCriterion("stock_detail_id between", value1, value2, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andStockDetailIdNotBetween(Long value1, Long value2) {
            addCriterion("stock_detail_id not between", value1, value2, "stockDetailId");
            return (Criteria) this;
        }

        public Criteria andDealNumberIsNull() {
            addCriterion("deal_number is null");
            return (Criteria) this;
        }

        public Criteria andDealNumberIsNotNull() {
            addCriterion("deal_number is not null");
            return (Criteria) this;
        }

        public Criteria andDealNumberEqualTo(BigDecimal value) {
            addCriterion("deal_number =", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberNotEqualTo(BigDecimal value) {
            addCriterion("deal_number <>", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberGreaterThan(BigDecimal value) {
            addCriterion("deal_number >", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deal_number >=", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberLessThan(BigDecimal value) {
            addCriterion("deal_number <", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deal_number <=", value, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberIn(List<BigDecimal> values) {
            addCriterion("deal_number in", values, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberNotIn(List<BigDecimal> values) {
            addCriterion("deal_number not in", values, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deal_number between", value1, value2, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andDealNumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deal_number not between", value1, value2, "dealNumber");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductCdIsNull() {
            addCriterion("product_cd is null");
            return (Criteria) this;
        }

        public Criteria andProductCdIsNotNull() {
            addCriterion("product_cd is not null");
            return (Criteria) this;
        }

        public Criteria andProductCdEqualTo(String value) {
            addCriterion("product_cd =", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdNotEqualTo(String value) {
            addCriterion("product_cd <>", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdGreaterThan(String value) {
            addCriterion("product_cd >", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdGreaterThanOrEqualTo(String value) {
            addCriterion("product_cd >=", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdLessThan(String value) {
            addCriterion("product_cd <", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdLessThanOrEqualTo(String value) {
            addCriterion("product_cd <=", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdLike(String value) {
            addCriterion("product_cd like", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdNotLike(String value) {
            addCriterion("product_cd not like", value, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdIn(List<String> values) {
            addCriterion("product_cd in", values, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdNotIn(List<String> values) {
            addCriterion("product_cd not in", values, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdBetween(String value1, String value2) {
            addCriterion("product_cd between", value1, value2, "productCd");
            return (Criteria) this;
        }

        public Criteria andProductCdNotBetween(String value1, String value2) {
            addCriterion("product_cd not between", value1, value2, "productCd");
            return (Criteria) this;
        }

        public Criteria andBrandNumberIsNull() {
            addCriterion("brand_number is null");
            return (Criteria) this;
        }

        public Criteria andBrandNumberIsNotNull() {
            addCriterion("brand_number is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNumberEqualTo(String value) {
            addCriterion("brand_number =", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberNotEqualTo(String value) {
            addCriterion("brand_number <>", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberGreaterThan(String value) {
            addCriterion("brand_number >", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberGreaterThanOrEqualTo(String value) {
            addCriterion("brand_number >=", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberLessThan(String value) {
            addCriterion("brand_number <", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberLessThanOrEqualTo(String value) {
            addCriterion("brand_number <=", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberLike(String value) {
            addCriterion("brand_number like", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberNotLike(String value) {
            addCriterion("brand_number not like", value, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberIn(List<String> values) {
            addCriterion("brand_number in", values, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberNotIn(List<String> values) {
            addCriterion("brand_number not in", values, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberBetween(String value1, String value2) {
            addCriterion("brand_number between", value1, value2, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andBrandNumberNotBetween(String value1, String value2) {
            addCriterion("brand_number not between", value1, value2, "brandNumber");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIsNull() {
            addCriterion("factory_id is null");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIsNotNull() {
            addCriterion("factory_id is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryIdEqualTo(Long value) {
            addCriterion("factory_id =", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotEqualTo(Long value) {
            addCriterion("factory_id <>", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdGreaterThan(Long value) {
            addCriterion("factory_id >", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("factory_id >=", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdLessThan(Long value) {
            addCriterion("factory_id <", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdLessThanOrEqualTo(Long value) {
            addCriterion("factory_id <=", value, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdIn(List<Long> values) {
            addCriterion("factory_id in", values, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotIn(List<Long> values) {
            addCriterion("factory_id not in", values, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdBetween(Long value1, Long value2) {
            addCriterion("factory_id between", value1, value2, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryIdNotBetween(Long value1, Long value2) {
            addCriterion("factory_id not between", value1, value2, "factoryId");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNull() {
            addCriterion("factory_name is null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIsNotNull() {
            addCriterion("factory_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryNameEqualTo(String value) {
            addCriterion("factory_name =", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotEqualTo(String value) {
            addCriterion("factory_name <>", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThan(String value) {
            addCriterion("factory_name >", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("factory_name >=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThan(String value) {
            addCriterion("factory_name <", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLessThanOrEqualTo(String value) {
            addCriterion("factory_name <=", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameLike(String value) {
            addCriterion("factory_name like", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotLike(String value) {
            addCriterion("factory_name not like", value, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameIn(List<String> values) {
            addCriterion("factory_name in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotIn(List<String> values) {
            addCriterion("factory_name not in", values, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameBetween(String value1, String value2) {
            addCriterion("factory_name between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andFactoryNameNotBetween(String value1, String value2) {
            addCriterion("factory_name not between", value1, value2, "factoryName");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIsNull() {
            addCriterion("warehouse_id is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIsNotNull() {
            addCriterion("warehouse_id is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdEqualTo(Long value) {
            addCriterion("warehouse_id =", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotEqualTo(Long value) {
            addCriterion("warehouse_id <>", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdGreaterThan(Long value) {
            addCriterion("warehouse_id >", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("warehouse_id >=", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdLessThan(Long value) {
            addCriterion("warehouse_id <", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdLessThanOrEqualTo(Long value) {
            addCriterion("warehouse_id <=", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIn(List<Long> values) {
            addCriterion("warehouse_id in", values, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotIn(List<Long> values) {
            addCriterion("warehouse_id not in", values, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdBetween(Long value1, Long value2) {
            addCriterion("warehouse_id between", value1, value2, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotBetween(Long value1, Long value2) {
            addCriterion("warehouse_id not between", value1, value2, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIsNull() {
            addCriterion("warehouse_name is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIsNotNull() {
            addCriterion("warehouse_name is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameEqualTo(String value) {
            addCriterion("warehouse_name =", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotEqualTo(String value) {
            addCriterion("warehouse_name <>", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameGreaterThan(String value) {
            addCriterion("warehouse_name >", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameGreaterThanOrEqualTo(String value) {
            addCriterion("warehouse_name >=", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLessThan(String value) {
            addCriterion("warehouse_name <", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLessThanOrEqualTo(String value) {
            addCriterion("warehouse_name <=", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLike(String value) {
            addCriterion("warehouse_name like", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotLike(String value) {
            addCriterion("warehouse_name not like", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIn(List<String> values) {
            addCriterion("warehouse_name in", values, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotIn(List<String> values) {
            addCriterion("warehouse_name not in", values, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameBetween(String value1, String value2) {
            addCriterion("warehouse_name between", value1, value2, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotBetween(String value1, String value2) {
            addCriterion("warehouse_name not between", value1, value2, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("updated_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("updated_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("updated_date =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("updated_date <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("updated_date >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_date >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("updated_date <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("updated_date <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("updated_date in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("updated_date not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("updated_date between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("updated_date not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Long value) {
            addCriterion("enterprise_id =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Long value) {
            addCriterion("enterprise_id <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Long value) {
            addCriterion("enterprise_id >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("enterprise_id >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Long value) {
            addCriterion("enterprise_id <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Long value) {
            addCriterion("enterprise_id <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Long> values) {
            addCriterion("enterprise_id in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Long> values) {
            addCriterion("enterprise_id not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Long value1, Long value2) {
            addCriterion("enterprise_id between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Long value1, Long value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdIsNull() {
            addCriterion("buy_company_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdIsNotNull() {
            addCriterion("buy_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdEqualTo(Long value) {
            addCriterion("buy_company_id =", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdNotEqualTo(Long value) {
            addCriterion("buy_company_id <>", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdGreaterThan(Long value) {
            addCriterion("buy_company_id >", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("buy_company_id >=", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdLessThan(Long value) {
            addCriterion("buy_company_id <", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("buy_company_id <=", value, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdIn(List<Long> values) {
            addCriterion("buy_company_id in", values, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdNotIn(List<Long> values) {
            addCriterion("buy_company_id not in", values, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdBetween(Long value1, Long value2) {
            addCriterion("buy_company_id between", value1, value2, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("buy_company_id not between", value1, value2, "buyCompanyId");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameIsNull() {
            addCriterion("buy_company_name is null");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameIsNotNull() {
            addCriterion("buy_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameEqualTo(String value) {
            addCriterion("buy_company_name =", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameNotEqualTo(String value) {
            addCriterion("buy_company_name <>", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameGreaterThan(String value) {
            addCriterion("buy_company_name >", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("buy_company_name >=", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameLessThan(String value) {
            addCriterion("buy_company_name <", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("buy_company_name <=", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameLike(String value) {
            addCriterion("buy_company_name like", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameNotLike(String value) {
            addCriterion("buy_company_name not like", value, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameIn(List<String> values) {
            addCriterion("buy_company_name in", values, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameNotIn(List<String> values) {
            addCriterion("buy_company_name not in", values, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameBetween(String value1, String value2) {
            addCriterion("buy_company_name between", value1, value2, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andBuyCompanyNameNotBetween(String value1, String value2) {
            addCriterion("buy_company_name not between", value1, value2, "buyCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdIsNull() {
            addCriterion("sell_company_id is null");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdIsNotNull() {
            addCriterion("sell_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdEqualTo(Long value) {
            addCriterion("sell_company_id =", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdNotEqualTo(Long value) {
            addCriterion("sell_company_id <>", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdGreaterThan(Long value) {
            addCriterion("sell_company_id >", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_company_id >=", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdLessThan(Long value) {
            addCriterion("sell_company_id <", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("sell_company_id <=", value, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdIn(List<Long> values) {
            addCriterion("sell_company_id in", values, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdNotIn(List<Long> values) {
            addCriterion("sell_company_id not in", values, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdBetween(Long value1, Long value2) {
            addCriterion("sell_company_id between", value1, value2, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("sell_company_id not between", value1, value2, "sellCompanyId");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameIsNull() {
            addCriterion("sell_company_name is null");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameIsNotNull() {
            addCriterion("sell_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameEqualTo(String value) {
            addCriterion("sell_company_name =", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameNotEqualTo(String value) {
            addCriterion("sell_company_name <>", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameGreaterThan(String value) {
            addCriterion("sell_company_name >", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("sell_company_name >=", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameLessThan(String value) {
            addCriterion("sell_company_name <", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("sell_company_name <=", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameLike(String value) {
            addCriterion("sell_company_name like", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameNotLike(String value) {
            addCriterion("sell_company_name not like", value, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameIn(List<String> values) {
            addCriterion("sell_company_name in", values, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameNotIn(List<String> values) {
            addCriterion("sell_company_name not in", values, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameBetween(String value1, String value2) {
            addCriterion("sell_company_name between", value1, value2, "sellCompanyName");
            return (Criteria) this;
        }

        public Criteria andSellCompanyNameNotBetween(String value1, String value2) {
            addCriterion("sell_company_name not between", value1, value2, "sellCompanyName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 21 10:36:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}