package com.spt.bas.report.client.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RptCtrContractRela {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long buyContractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long buyProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private BigDecimal buyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long buyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String buyUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Date buyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long sellContractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long sellProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private BigDecimal sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long sellUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String sellUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Date sellDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.stock_detail_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long stockDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.deal_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private BigDecimal dealNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.product_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.product_cd
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String productCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.brand_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String brandNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.factory_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.factory_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.warehouse_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.warehouse_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.created_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.updated_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.enterprise_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long buyCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.buy_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String buyCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private Long sellCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_contract_rela.sell_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    private String sellCompanyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.id
     *
     * @return the value of t_ctr_contract_rela.id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.id
     *
     * @param id the value for t_ctr_contract_rela.id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_contract_id
     *
     * @return the value of t_ctr_contract_rela.buy_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getBuyContractId() {
        return buyContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_contract_id
     *
     * @param buyContractId the value for t_ctr_contract_rela.buy_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyContractId(Long buyContractId) {
        this.buyContractId = buyContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_product_id
     *
     * @return the value of t_ctr_contract_rela.buy_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getBuyProductId() {
        return buyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_product_id
     *
     * @param buyProductId the value for t_ctr_contract_rela.buy_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyProductId(Long buyProductId) {
        this.buyProductId = buyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_price
     *
     * @return the value of t_ctr_contract_rela.buy_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_price
     *
     * @param buyPrice the value for t_ctr_contract_rela.buy_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_user_id
     *
     * @return the value of t_ctr_contract_rela.buy_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getBuyUserId() {
        return buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_user_id
     *
     * @param buyUserId the value for t_ctr_contract_rela.buy_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyUserId(Long buyUserId) {
        this.buyUserId = buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_user_name
     *
     * @return the value of t_ctr_contract_rela.buy_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getBuyUserName() {
        return buyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_user_name
     *
     * @param buyUserName the value for t_ctr_contract_rela.buy_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyUserName(String buyUserName) {
        this.buyUserName = buyUserName == null ? null : buyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_date
     *
     * @return the value of t_ctr_contract_rela.buy_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_date
     *
     * @param buyDate the value for t_ctr_contract_rela.buy_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_contract_id
     *
     * @return the value of t_ctr_contract_rela.sell_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getSellContractId() {
        return sellContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_contract_id
     *
     * @param sellContractId the value for t_ctr_contract_rela.sell_contract_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellContractId(Long sellContractId) {
        this.sellContractId = sellContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_product_id
     *
     * @return the value of t_ctr_contract_rela.sell_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getSellProductId() {
        return sellProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_product_id
     *
     * @param sellProductId the value for t_ctr_contract_rela.sell_product_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellProductId(Long sellProductId) {
        this.sellProductId = sellProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_price
     *
     * @return the value of t_ctr_contract_rela.sell_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_price
     *
     * @param sellPrice the value for t_ctr_contract_rela.sell_price
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_user_id
     *
     * @return the value of t_ctr_contract_rela.sell_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getSellUserId() {
        return sellUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_user_id
     *
     * @param sellUserId the value for t_ctr_contract_rela.sell_user_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellUserId(Long sellUserId) {
        this.sellUserId = sellUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_user_name
     *
     * @return the value of t_ctr_contract_rela.sell_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getSellUserName() {
        return sellUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_user_name
     *
     * @param sellUserName the value for t_ctr_contract_rela.sell_user_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellUserName(String sellUserName) {
        this.sellUserName = sellUserName == null ? null : sellUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_date
     *
     * @return the value of t_ctr_contract_rela.sell_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Date getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_date
     *
     * @param sellDate the value for t_ctr_contract_rela.sell_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.stock_detail_id
     *
     * @return the value of t_ctr_contract_rela.stock_detail_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getStockDetailId() {
        return stockDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.stock_detail_id
     *
     * @param stockDetailId the value for t_ctr_contract_rela.stock_detail_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setStockDetailId(Long stockDetailId) {
        this.stockDetailId = stockDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.deal_number
     *
     * @return the value of t_ctr_contract_rela.deal_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public BigDecimal getDealNumber() {
        return dealNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.deal_number
     *
     * @param dealNumber the value for t_ctr_contract_rela.deal_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setDealNumber(BigDecimal dealNumber) {
        this.dealNumber = dealNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.product_name
     *
     * @return the value of t_ctr_contract_rela.product_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.product_name
     *
     * @param productName the value for t_ctr_contract_rela.product_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.product_cd
     *
     * @return the value of t_ctr_contract_rela.product_cd
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.product_cd
     *
     * @param productCd the value for t_ctr_contract_rela.product_cd
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd == null ? null : productCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.brand_number
     *
     * @return the value of t_ctr_contract_rela.brand_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getBrandNumber() {
        return brandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.brand_number
     *
     * @param brandNumber the value for t_ctr_contract_rela.brand_number
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBrandNumber(String brandNumber) {
        this.brandNumber = brandNumber == null ? null : brandNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.factory_id
     *
     * @return the value of t_ctr_contract_rela.factory_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.factory_id
     *
     * @param factoryId the value for t_ctr_contract_rela.factory_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setFactoryId(Long factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.factory_name
     *
     * @return the value of t_ctr_contract_rela.factory_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.factory_name
     *
     * @param factoryName the value for t_ctr_contract_rela.factory_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.warehouse_id
     *
     * @return the value of t_ctr_contract_rela.warehouse_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.warehouse_id
     *
     * @param warehouseId the value for t_ctr_contract_rela.warehouse_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.warehouse_name
     *
     * @return the value of t_ctr_contract_rela.warehouse_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.warehouse_name
     *
     * @param warehouseName the value for t_ctr_contract_rela.warehouse_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.created_date
     *
     * @return the value of t_ctr_contract_rela.created_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.created_date
     *
     * @param createdDate the value for t_ctr_contract_rela.created_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.updated_date
     *
     * @return the value of t_ctr_contract_rela.updated_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.updated_date
     *
     * @param updatedDate the value for t_ctr_contract_rela.updated_date
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.enterprise_id
     *
     * @return the value of t_ctr_contract_rela.enterprise_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.enterprise_id
     *
     * @param enterpriseId the value for t_ctr_contract_rela.enterprise_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_company_id
     *
     * @return the value of t_ctr_contract_rela.buy_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getBuyCompanyId() {
        return buyCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_company_id
     *
     * @param buyCompanyId the value for t_ctr_contract_rela.buy_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyCompanyId(Long buyCompanyId) {
        this.buyCompanyId = buyCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.buy_company_name
     *
     * @return the value of t_ctr_contract_rela.buy_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getBuyCompanyName() {
        return buyCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.buy_company_name
     *
     * @param buyCompanyName the value for t_ctr_contract_rela.buy_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setBuyCompanyName(String buyCompanyName) {
        this.buyCompanyName = buyCompanyName == null ? null : buyCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_company_id
     *
     * @return the value of t_ctr_contract_rela.sell_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public Long getSellCompanyId() {
        return sellCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_company_id
     *
     * @param sellCompanyId the value for t_ctr_contract_rela.sell_company_id
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellCompanyId(Long sellCompanyId) {
        this.sellCompanyId = sellCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_contract_rela.sell_company_name
     *
     * @return the value of t_ctr_contract_rela.sell_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public String getSellCompanyName() {
        return sellCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_contract_rela.sell_company_name
     *
     * @param sellCompanyName the value for t_ctr_contract_rela.sell_company_name
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    public void setSellCompanyName(String sellCompanyName) {
        this.sellCompanyName = sellCompanyName == null ? null : sellCompanyName.trim();
    }
}