package com.spt.bas.report.server.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.spt.bas.report.client.entity.RptCtrContractRela;
import com.spt.bas.report.client.entity.RptCtrContractRelaExample;
import com.spt.tools.mybatis.annotation.MyBatisDao;
@MyBatisDao
public interface RptCtrContractRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    long countByExample(RptCtrContractRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int deleteByExample(RptCtrContractRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int insert(RptCtrContractRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int insertSelective(RptCtrContractRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    List<RptCtrContractRela> selectByExample(RptCtrContractRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    RptCtrContractRela selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") RptCtrContractRela record, @Param("example") RptCtrContractRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int updateByExample(@Param("record") RptCtrContractRela record, @Param("example") RptCtrContractRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int updateByPrimaryKeySelective(RptCtrContractRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_contract_rela
     *
     * @mbg.generated Tue Aug 21 10:36:01 CST 2018
     */
    int updateByPrimaryKey(RptCtrContractRela record);
}